apiVersion: v1
kind: ServiceAccount
metadata:
  name: erpnext-assets-builder
  namespace: {{ .Release.Namespace }}
  labels:
    app: erpnext-assets-builder
{{ include "erpnext.labels" . | indent 4 }}
