apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
{{ include "erpnext.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
