apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mariadb
{{ include "erpnext.labels" . | indent 4 }}
spec:
  serviceName: {{ .Values.mariadb.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
{{ include "erpnext.labels" . | indent 8 }}
    spec:
      containers:
        - name: mariadb
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mariadb.service.port }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: mariadb-root-password
          resources:
{{ toYaml .Values.mariadb.resources | indent 12 }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mariadb.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mariadb.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
