apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: erpnext-allow-frontend-egress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "erpnext.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app: websocket
      ports:
        - protocol: TCP
          port: 9000