apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: erpnext-allow-workers-egress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "erpnext.labels" . | indent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - queue-short
          - queue-long
          - scheduler
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app: mariadb
      ports:
        - protocol: TCP
          port: 3306
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app: redis-queue
      ports:
        - protocol: TCP
          port: 6379