{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.azureKeyVault.secretProviderClassName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: erpnext
{{ include "erpnext.labels" . | indent 4 }}
spec:
  provider: azure
{{- if .Values.azureKeyVault.syncKubernetesSecret.enabled }}
  secretObjects:
    - secretName: {{ .Values.azureKeyVault.syncKubernetesSecret.name }}
      type: Opaque
      data:
        - objectName: {{ .Values.azureKeyVault.objects.mariadbRootPassword.objectName }}
          key: mariadb-root-password
        - objectName: {{ .Values.azureKeyVault.objects.adminPassword.objectName }}
          key: admin-password
        - objectName: {{ .Values.azureKeyVault.objects.dbPassword.objectName }}
          key: db-password
{{- if .Values.azureKeyVault.objects.demoRotatingSecret.enabled }}
        - objectName: {{ .Values.azureKeyVault.objects.demoRotatingSecret.objectName }}
          key: {{ .Values.azureKeyVault.objects.demoRotatingSecret.secretKey }}
{{- end }}
{{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azureKeyVault.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.azureKeyVault.keyVaultName | quote }}
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.azureKeyVault.objects.mariadbRootPassword.objectName }}
          objectType: {{ .Values.azureKeyVault.objects.mariadbRootPassword.objectType }}
        - |
          objectName: {{ .Values.azureKeyVault.objects.adminPassword.objectName }}
          objectType: {{ .Values.azureKeyVault.objects.adminPassword.objectType }}
        - |
          objectName: {{ .Values.azureKeyVault.objects.dbPassword.objectName }}
          objectType: {{ .Values.azureKeyVault.objects.dbPassword.objectType }}
{{- if .Values.azureKeyVault.objects.demoRotatingSecret.enabled }}
        - |
          objectName: {{ .Values.azureKeyVault.objects.demoRotatingSecret.objectName }}
          objectType: {{ .Values.azureKeyVault.objects.demoRotatingSecret.objectType }}
{{- end }}
{{- end }}
