{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: erpnext-site-secret
{{ include "erpnext.labels" . | indent 4 }}
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.secret.mariadbRootPassword | quote }}
  admin-password: {{ .Values.secret.adminPassword | quote }}
  db-password: {{ .Values.secret.dbPassword | quote }}
{{- end }}
