apiVersion: v1
kind: ServiceAccount
metadata:
  name: erpnext-workload
  namespace: {{ .Release.Namespace }}
  labels:
    app: erpnext-workload
{{ include "erpnext.labels" . | indent 4 }}
automountServiceAccountToken: false
