apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.azureKeyVault.serviceAccountName | default "erpnext-workload" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: erpnext-workload
{{- if .Values.azureKeyVault.enabled }}
    azure.workload.identity/use: "true"
{{- end }}
{{ include "erpnext.labels" . | indent 4 }}
{{- if .Values.azureKeyVault.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureKeyVault.managedIdentityClientId | quote }}
{{- end }}
automountServiceAccountToken: {{ ternary true false .Values.azureKeyVault.enabled }}
