apiVersion: v1
kind: Secret
metadata:
  name: erpnext-site-secret
  namespace: erpnext-gitops
type: Opaque
stringData:
  mariadb-root-password: "CHANGE_ME_MARIADB_ROOT_PASSWORD"
  admin-password: "CHANGE_ME_ADMIN_PASSWORD"
  db-password: "CHANGE_ME_DB_PASSWORD"
