apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: default
  labels:
    app: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: frappe/erpnext:v16.35.0

          command:
            - node
            - /home/frappe/frappe-bench/apps/frappe/socketio.js

          ports:
            - name: socketio
              containerPort: 9000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites

      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: sites
