apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: default
  labels:
    app: websocket
spec:
  type: ClusterIP
  selector:
    app: websocket
  ports:
    - name: socketio
      port: 9000
      targetPort: 9000
      protocol: TCP
