grafana:
  enabled: true

alertmanager:
  enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

kubeStateMetrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
